import { useEffect, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { api } from '../api'
import Breadcrumbs from '../components/Breadcrumbs'
import MappedRobRubTable from '../components/MappedRobRubTable'
import StatusBadge from '../components/StatusBadge'

const newRow=()=>({id:crypto.randomUUID(),value:''})
export default function CertificationPage(){
 const {upc}=useParams(),navigate=useNavigate();const [project,setProject]=useState(null),[decision,setDecision]=useState(''),[rows,setRows]=useState([newRow()]),[results,setResults]=useState([]),[message,setMessage]=useState(''),[error,setError]=useState(''),[saving,setSaving]=useState(false),[deletingId,setDeletingId]=useState('')
 useEffect(()=>{api.getProject(upc).then(setProject).catch(e=>setError(e.message))},[upc])
 async function save(event){event.preventDefault();const ids=rows.map(row=>row.value.trim()).filter(Boolean);if(!ids.length)return setError('Enter at least one ROB/RUB ID.');if(new Set(ids).size!==ids.length)return setError('Enter each ROB/RUB ID only once.');setSaving(true);try{const data=await api.createMappings(upc,ids);setResults(data.results);const saved=data.saved_records||[];setProject(current=>{const merged=[...(current.mappings||[])];for(const record of saved){if(!merged.some(existing=>existing.proposal_id===record.proposal_id))merged.push(record)}return {...current,mappings:merged,mapped_rob_rub_count:merged.length}});if(saved.length)setRows([newRow()]);setError('')}catch(e){setError(e.message)}finally{setSaving(false)}}
 async function certify(status){if(!window.confirm(status==='certified'?'Certify this project?':'Reopen this project?'))return;try{const data=await api.setCertification(upc,status);setProject(data);setMessage(status==='certified'?'Project certified successfully.':'Project reopened successfully.')}catch(e){setError(e.message)}}
 async function deleteMapping(proposalId){if(!window.confirm(`Delete mapping ${proposalId} from this project?`))return;setDeletingId(proposalId);try{await api.deleteMapping(upc,proposalId);setProject(current=>{const mappings=(current.mappings||[]).filter(record=>record.proposal_id!==proposalId);return {...current,mappings,mapped_rob_rub_count:mappings.length}});setMessage(`Mapping ${proposalId} deleted. The master record is unchanged.`);setError('')}catch(e){setError(e.message)}finally{setDeletingId('')}}
 if(error&&!project)return <div className="alert error">{error}</div>;if(!project)return <p>Loading project…</p>
 return <><Breadcrumbs items={[{label:'Projects',to:'/projects'},{label:project.ro},{label:project.piu},{label:project.upc},{label:'Certification'}]}/><div className="page-actions"><button className="button secondary" onClick={()=>navigate(-1)}>← Back</button><Link className="button secondary" to="/rob-rubs">View complete ROB/RUB database</Link></div><section className="page-heading"><h1>{project.project_name}</h1><p>{project.upc} · <StatusBadge status={project.certification_status}/> · {project.mapped_rob_rub_count} mapped</p></section><section className="card">{project.certification_status==='certified'?<><h2>This project is certified</h2><button className="button warning" onClick={()=>certify('pending')}>Reopen project</button></>:<><h2>Are there any ROBs/RUBs in this project?</h2><p>Choose one option before proceeding with certification.</p><div className="choice-row"><button className={`button ${decision==='yes'?'active':''}`} onClick={()=>setDecision('yes')}>Yes, map ROBs/RUBs</button><button className={`button ${decision==='no'?'active':''}`} onClick={()=>setDecision('no')}>No ROBs/RUBs</button></div>{decision==='yes'&&<form onSubmit={save} className="branch"><h3>Map ROBs/RUBs</h3>{rows.map((row,index)=><div className="id-row" key={row.id}><label>ROB/RUB Proposal ID {index+1}<input value={row.value} onChange={event=>setRows(current=>current.map(item=>item.id===row.id?{...item,value:event.target.value}:item))}/></label>{rows.length>1&&<button type="button" className="remove-button" onClick={()=>setRows(current=>current.filter(item=>item.id!==row.id))}>Remove</button>}</div>)}<button type="button" className="button secondary" disabled={saving} onClick={()=>setRows(current=>[...current,newRow()])}>+ Add another ROB/RUB</button><button className="button" type="submit" disabled={saving}>{saving?'Saving…':'Save mappings'}</button>{results.map((result,index)=><div className={`result ${result.status}`} key={`${result.proposal_id}-${index}`}>{result.proposal_id}: {result.message}</div>)}{project.mapped_rob_rub_count>0&&<button type="button" className="button certify" onClick={()=>certify('certified')}>Certify project</button>}</form>}{decision==='no'&&<div className="branch"><h3>Certify without ROB/RUB mapping</h3><p>This project will be certified with zero mappings.</p><button className="button certify" onClick={()=>certify('certified')}>Certify project</button></div>}</>}<MappedRobRubTable records={project.mappings} canDelete={project.certification_status==='pending'} deletingId={deletingId} onDelete={deleteMapping}/>{error&&<div className="alert error">{error}</div>}{message&&<div className="alert success">{message}</div>}</section></>
}
