import { useEffect, useState } from 'react'
import { api } from '../api'
import Breadcrumbs from '../components/Breadcrumbs'
import Pagination from '../components/Pagination'

export default function RobRubDatabasePage(){
 const [filters,setFilters]=useState({states:[],categories:[],divisions:[]}),[values,setValues]=useState({search:'',state:'',category:'',division:'',mapping_status:'all'}),[page,setPage]=useState(1),[data,setData]=useState({items:[],total:0}),[error,setError]=useState(''),[loading,setLoading]=useState(true),[refresh,setRefresh]=useState(0)
 useEffect(()=>{api.getRobRubFilters().then(setFilters).catch(e=>setError(e.message))},[])
 useEffect(()=>{const timer=setTimeout(()=>{setLoading(true);api.getRobRubs({...values,page,page_size:25}).then(setData).catch(e=>setError(e.message)).finally(()=>setLoading(false))},300);return()=>clearTimeout(timer)},[values,page,refresh])
 function update(field,value){setValues(v=>({...v,[field]:value}));setPage(1)}
 return <><Breadcrumbs items={[{label:'ROB/RUB Database'}]}/><section className="page-heading"><h1>Complete ROB/RUB database</h1><p>Search and filter the entire master register.</p></section><section className="card"><div className="filters register"><label>Search all fields<input value={values.search} onChange={e=>update('search',e.target.value)} placeholder="Proposal ID, work, state…"/></label><Filter label="State" value={values.state} options={filters.states} onChange={v=>update('state',v)}/><Filter label="Category" value={values.category} options={filters.categories} onChange={v=>update('category',v)}/><Filter label="Division/Railway" value={values.division} options={filters.divisions} onChange={v=>update('division',v)}/><label>Mapping Status<select value={values.mapping_status} onChange={e=>update('mapping_status',e.target.value)}><option value="all">All</option><option value="mapped">Mapped</option><option value="pending">Pending</option></select></label></div>
 {error&&<div className="alert error">{error} <button onClick={()=>setRefresh(x=>x+1)}>Retry</button></div>}{loading?<p>Loading ROB/RUB records…</p>:<><div className="table-scroll"><table><thead><tr><th>Proposal ID</th><th>Proposal Date</th><th>Name of Work</th><th>Division/Railway</th><th>State</th><th>Road Authority</th><th>Category</th><th>Name of Road</th><th>Mapping</th><th>Mapped Project</th></tr></thead><tbody>{data.items.map(r=><tr key={r.proposal_id}><td>{r.proposal_id}</td><td>{r.proposal_date||'—'}</td><td>{r.name_of_work||'—'}</td><td>{r.division_railway||'—'}</td><td>{r.state||'—'}</td><td>{r.associated_road_authority||'—'}</td><td>{r.category_of_road||'—'}</td><td>{r.name_of_road||'—'}</td><td>{r.mapping_status}</td><td>{r.mapped_project_name||r.mapped_upc||'—'}</td></tr>)}</tbody></table>{data.items.length===0&&<p className="empty">No ROB/RUB records match these filters.</p>}</div><Pagination page={page} pageSize={25} total={data.total} onPageChange={setPage}/></>}</section></>
}
function Filter({label,value,options,onChange}){return <label>{label}<select value={value} onChange={e=>onChange(e.target.value)}><option value="">All</option>{options.map(x=><option key={x}>{x}</option>)}</select></label>}
